[package]
name = "DEngine"
version = "0.0.1"
edition = "2021"

[profile.dev]
opt-level = 3

[dependencies]
vulkano = "*"
vulkano-shaders = "*"

cgmath = { version = "*", features = ["serde"] }
winit = "0.28.7"

serde = {version = "*", features = ["std", "derive"]}
